### ISSUE TITLE
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]  https://next-auth.js.org/errors#oauth_callback_handler_error 5 NOT_FOUND: 

### ISSUE THREAD

**Issue by raviada4440** [Mohamed-lifa7/next-drive#1]
I am getting this error while trying either GitHub or Google oAuth.

```
[next-auth][debug][adapter_getUserByAccount] { args: [ { providerAccountId: '86073734', provider: 'github' } ] }
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount 5 NOT_FOUND:  {
  message: '5 NOT_FOUND: ',
  stack: 'Error: 5 NOT_FOUND: \n' +
    '    at callErrorFromStatus (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n' +
    '    at Object.onReceiveStatus (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/client.js:357:73)\n' +
    '    at Object.onReceiveStatus (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n' +
    '    at /Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\n' +
    'for call at\n' +
    '    at ServiceClientImpl.makeServerStreamRequest (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/client.js:340:32)\n' +
    '    at ServiceClientImpl.<anonymous> (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n' +
    '    at /Users/ravi.ada/projects/play/next-drive/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29\n' +
    '    at /Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28\n' +
    '    at /Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16\n' +
    '    at Object.request (/Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)\n' +
    '    at makeRequest (/Users/ravi.ada/projects/play/next-drive/node_modules/retry-request/index.js:141:28)\n' +
    '    at retryRequest (/Users/ravi.ada/projects/play/next-drive/node_modules/retry-request/index.js:109:5)\n' +
    '    at StreamProxy.setStream (/Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streaming.js:121:37)\n' +
    '    at StreamingApiCaller.call (/Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:54:16)\n' +
    '    at /Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/createApiCall.js:84:30\n' +
    'Caused by: Error\n' +
    '    at Query._get (/Users/ravi.ada/projects/play/next-drive/node_modules/@google-cloud/firestore/build/src/reference.js:1719:23)\n' +
    '    at Query.get (/Users/ravi.ada/projects/play/next-drive/node_modules/@google-cloud/firestore/build/src/reference.js:1707:21)\n' +
    '    at getOneDoc (webpack-internal:///(rsc)/./node_modules/@auth/firebase-adapter/index.js:259:52)\n' +
    '    at getUserByAccount (webpack-internal:///(rsc)/./node_modules/@auth/firebase-adapter/index.js:126:35)\n' +
    '    at _callee2$ (webpack-internal:///(rsc)/./node_modules/next-auth/core/errors.js:301:43)\n' +
    '    at tryCatch (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:36:24)\n' +
    '    at Generator.eval (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:123:25)\n' +
    '    at Generator.eval [as next] (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:64:29)\n' +
    '    at asyncGeneratorStep (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:4:28)\n' +
    '    at _next (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:17)\n' +
    '    at eval (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:13)\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at eval (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:16)\n' +
    '    at Object.callback (webpack-internal:///(rsc)/./node_modules/next-auth/core/routes/callback.js:42:49)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async AuthHandler (webpack-internal:///(rsc)/./node_modules/next-auth/core/index.js:202:38)\n' +
    '    at async NextAuthRouteHandler (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:50:30)\n' +
    '    at async NextAuth._args$ (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:85:24)\n' +
    '    at async /Users/ravi.ada/projects/play/next-drive/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62361',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 5 NOT_FOUND:  Error: 5 NOT_FOUND: 
    at callErrorFromStatus (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/client.js:357:73)
    at Object.onReceiveStatus (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/client.js:340:32)
    at ServiceClientImpl.<anonymous> (/Users/ravi.ada/projects/play/next-drive/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /Users/ravi.ada/projects/play/next-drive/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29
    at /Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
    at makeRequest (/Users/ravi.ada/projects/play/next-drive/node_modules/retry-request/index.js:141:28)
    at retryRequest (/Users/ravi.ada/projects/play/next-drive/node_modules/retry-request/index.js:109:5)
    at StreamProxy.setStream (/Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streaming.js:121:37)
    at StreamingApiCaller.call (/Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:54:16)
    at /Users/ravi.ada/projects/play/next-drive/node_modules/google-gax/build/src/createApiCall.js:84:30
Caused by: Error
    at Query._get (/Users/ravi.ada/projects/play/next-drive/node_modules/@google-cloud/firestore/build/src/reference.js:1719:23)
    at Query.get (/Users/ravi.ada/projects/play/next-drive/node_modules/@google-cloud/firestore/build/src/reference.js:1707:21)
    at getOneDoc (webpack-internal:///(rsc)/./node_modules/@auth/firebase-adapter/index.js:259:52)
    at getUserByAccount (webpack-internal:///(rsc)/./node_modules/@auth/firebase-adapter/index.js:126:35)
    at _callee2$ (webpack-internal:///(rsc)/./node_modules/next-auth/core/errors.js:301:43)
    at tryCatch (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:36:24)
    at Generator.eval (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:123:25)
    at Generator.eval [as next] (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:64:29)
    at asyncGeneratorStep (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:4:28)
    at _next (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:17)
    at eval (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:13)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:16)
    at Object.callback (webpack-internal:///(rsc)/./node_modules/next-auth/core/routes/callback.js:42:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthHandler (webpack-internal:///(rsc)/./node_modules/next-auth/core/index.js:202:38)
    at async NextAuthRouteHandler (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:50:30)
    at async NextAuth._args$ (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:85:24)
    at async /Users/ravi.ada/projects/play/next-drive/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62361 {
  name: 'GetUserByAccountError',
  code: 5
}

```

**Comment by mohamed-lifa7** [comment]
I'm having difficulty understanding the details. Could you please reach out to me at mohamedlifa7@gmail.com ? I'd appreciate it if we could discuss the matter further to ensure I address the issue appropriately.
